In [3]:
import numpy as np
a=np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
 def f(x, y):
return 10 * x + y

IndentationError: expected an indented block (Temp/ipykernel_3688/1117123762.py, line 2)

In [6]:
def f(x, y):
... return 10 * x + y
...

IndentationError: expected an indented block (Temp/ipykernel_3688/3221276140.py, line 2)

In [7]:
def f(x, y):return 10 * x + y


In [8]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [9]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [10]:
b[0:5, 1] 

array([ 1, 11, 21, 31, 41])

In [11]:
b[-1]

array([40, 41, 42, 43])

In [ ]:
import numpy as np


# creating an array using numpy 

In [13]:
food = np.array(["pakora","samosa", "riata"])
food

array(['pakora', 'samosa', 'riata'], dtype='<U6')

In [14]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [15]:
type(price)

numpy.ndarray

In [16]:
type(food)

numpy.ndarray

In [17]:
len(price)

3

In [19]:
price[2]

5

In [20]:
price[:]

array([5, 5, 5])

In [21]:
food[1]

'samosa'

In [22]:
price.mean()

5.0

In [23]:
# zeros

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [27]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [28]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [29]:
np.empty(2)

array([2.12199579e-314, 6.36598737e-314])

In [33]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [36]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# array with specific line space

In [39]:
np.linspace(1,30, num=5)

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [40]:
#specufy your datatype
np.ones(5, dtype= np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [41]:
np.ones(15, dtype= np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Functions

In [43]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [45]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [50]:
b= np.array([10.2,3,7,1,4.5,2])
b

array([10.2,  3. ,  7. ,  1. ,  4.5,  2. ])

In [51]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3. ,   7. ,   1. ,   4.5,   2. ])

In [54]:
d=np.concatenate((b,a))
d

array([ 10.2,   3. ,   7. ,   1. ,   4.5,   2. ,   0.5,   2. ,   4. ,
         6. ,  10. ,  10.3,  12. ,  15. , 100. , 320. ])

In [78]:
a = np.array([[4,5],[7,8]])
a

array([[4, 5],
       [7, 8]])

In [79]:
c=np.array([[6,7],[8,9]])
c

array([[6, 7],
       [8, 9]])

In [84]:
d=np.concatenate((a,c),axis=1)
d

array([[4, 5, 6, 7],
       [7, 8, 8, 9]])

In [82]:
a.ndim

2

In [86]:
d.ndim

2

In [91]:
f=np.array([[[6,7],[8,9]],[[6,7],[8,9]]])
f


array([[[6, 7],
        [8, 9]],

       [[6, 7],
        [8, 9]]])

In [92]:
f.ndim

3

In [95]:
b= a.reshape(2,2)
b

array([[4, 5],
       [7, 8]])

In [97]:
# covert 1 D into 2 D....

In [100]:
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [102]:
a=b[np.newaxis,:]
a

array([[[4, 5],
        [7, 8]]])

In [104]:
a.shape


(1, 2, 2)

In [106]:
g=b[:,np.newaxis]
g

array([[[4, 5]],

       [[7, 8]]])

In [107]:
g*6


array([[[24, 30]],

       [[42, 48]]])

In [108]:
g.sum()

24

In [109]:
g.mean()

6.0